import volokitinImage from 'talks-image-responsive!./images/volokitin.jpg';
import kazakovImage from 'talks-image-responsive!./images/kazakov.jpg';
import chevdarImage from 'talks-image-responsive!./images/chevdar.jpg';
import tihonovImage from 'talks-image-responsive!./images/tihonov.jpg';
import burmistrovImage from 'talks-image-responsive!./images/burmistrov.jpg';
import egorovImage from 'talks-image-responsive!./images/egorov.jpg';
import larkovImage from 'talks-image-responsive!./images/larkov.jpg';
import ronzhinaImage from 'talks-image-responsive!./images/ronzhina.png';
import ratkinImage from 'talks-image-responsive!./images/ratkin.png';
import golubevImage from 'talks-image-responsive!./images/golubev.png';
import moiseevImage from 'talks-image-responsive!./images/moiseev.png';
import konovalovImage from 'talks-image-responsive!./images/konovalov.png';
import sobolevaImage from 'talks-image-responsive!./images/soboleva.jpg';
import vdovichenkoImage from 'talks-image-responsive!./images/vdovichenko.png';
import kirpichnikovImage from 'talks-image-responsive!./images/kirpichnikov.jpg';
import khruschevImage from 'talks-image-responsive!./images/khruschev.jpg';

export default {
    title: 'Выступления',
    meta: [
        { ['http-equiv']: 'content-language', ['content']: 'ru-RU' },
        { ['name']: 'description', ['content']: 'Записи докладов с конференции от компании СКБ Контур' },
        { ['name']: 'keywords', ['content']: 'видео,технологии,доклад,скб контур' },
    ],
    items: [
        {
            image: volokitinImage,
            speakerFullName: 'Павел Волокитин',
            eventName: 'FrontendFellows',
            title: 'Relay или не Relay',
            dateString: 'январь 2016',
            tags: ['frontend', 'js', 'react'],
            linkToVideo: 'https://www.youtube.com/watch?v=v5Fi-djuwZk',
            linkToSlides: 'http://www.slideshare.net/PavelVolokitin/frontfellows-relay-66758880',
        },
        {
            image: kazakovImage,
            speakerFullName: 'Александр Казаков',
            eventName: 'Codefest',
            title: 'Нетривиальное о репликации: как добиться высокой доступности',
            dateString: 'март 2016',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=LFpJGGs-kuo',
            linkToSlides: 'http://www.slideshare.net/codefest/ss-60114851',
        },
        {
            image: chevdarImage,
            speakerFullName: 'Игорь Чевдарь',
            eventName: 'DotNext',
            title: 'Кодогенерация для оптимизации',
            dateString: 'июнь 2016',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=X35JVTJV1CE&list=PLtWrKx3nUGBeYn-pSCjEgBPL90SvpylZL&index=7',
            linkToSlides: 'http://public.jugru.org/dotnext/2016/spb/day_1/track_2/chevdar.pdf',
        },
        {
            image: volokitinImage,
            speakerFullName: 'Павел Волокитин',
            eventName: 'WebStandartsDays',
            title: 'Меняем JavaScript с помощью JavaScript',
            dateString: 'июнь 2016',
            tags: ['frontend', 'js'],
            linkToVideo: 'https://www.youtube.com/watch?v=zoq95j3V43g',
            linkToSlides: 'http://www.slideshare.net/PavelVolokitin/javascript-javascript-66759016',
        },
        {
            image: tihonovImage,
            speakerFullName: 'Евгений Тихонов',
            eventName: 'WebStandartsDays',
            title: 'Готовим бизнес-лапшу на React и Redux',
            dateString: 'июнь 2016',
            tags: ['frontend', 'js', 'react'],
            linkToVideo: 'https://www.youtube.com/watch?v=OXsxo4gkqtQ',
            linkToSlides: 'https://reelm.github.io/wsd-2016-slides/wsd-2016-slides.zip',
        },
        {
            image: burmistrovImage,
            speakerFullName: 'Иван Бурмистров',
            eventName: 'Cassandra Summit',
            title: 'Digging Cassandra cluster',
            dateString: 'сентябрь 2015',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=t6utdWssBOM',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQX1FvSlgtaUtscFE',
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: 'SECR',
            title: 'Почему вам стоит организовать свою ИТ-конференцию и как это сделать',
            dateString: 'октябрь 2015',
            tags: ['management', 'education'],
            linkToVideo: 'http://0x1.tv/20151022BG',
            linkToSlides: 'http://0x1.tv/20151022BG',
        },
        {
            image: kazakovImage,
            speakerFullName: 'Александр Казаков',
            eventName: 'DUMP',
            title: 'Профилирование распределенных систем',
            dateString: 'апрель 2016',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=EpDgUZWjGLc&index=6&list=PLRdS-n5seLRriePAvTXvkl8mE20gPeDIp',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQY1Bpdi1PTndhOXc',
        },
        {
            image: larkovImage,
            speakerFullName: 'Алексей Ларьков',
            eventName: 'DUMP',
            title: 'Moira: Realtime alerting',
            dateString: 'апрель 2016',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=_MJdtHbiXPE&index=5&list=PLRdS-n5seLRriePAvTXvkl8mE20gPeDIp',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQQVcwUEpybmpIZVE/view?usp=drivesdk',
        },
        {
            image: ronzhinaImage,
            speakerFullName: 'Анастасия Ронжина',
            eventName: 'DUMP',
            title: 'Cообщество тестировщиков Екатеринбурга',
            dateString: 'апрель 2016',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=-4zAc7kWAhc&index=5&list=PLRdS-n5seLRoMRdNO1k1FeFeBMgBRRX6j',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQRmF5dHVuWU8tYlU',
        },
        {
            image: ratkinImage,
            speakerFullName: 'Кирилл Раткин',
            eventName: 'DUMP',
            title: 'Планирование развития автотестов',
            dateString: 'апрель 2016',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=4yrWt_b835k&index=4&list=PLRdS-n5seLRoMRdNO1k1FeFeBMgBRRX6j',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQSHRBaGhKVjRhMkE',
        },
        {
            image: golubevImage,
            speakerFullName: 'Александр Голубев',
            eventName: 'DUMP',
            title: 'Адаптация команды после увольнения сотрудников',
            dateString: 'апрель 2016',
            tags: ['management', 'hr'],
            linkToVideo: 'https://www.youtube.com/watch?v=pL6AFI5GpqM&index=3&list=PLRdS-n5seLRrEr-0A2koGR1a2tM9dM0an',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQQkxlNXRPZTFjRTA',
        },
        {
            image: moiseevImage,
            speakerFullName: 'Дмитрий Моисеев',
            eventName: 'DUMP',
            title: 'Xamarin: кроссплатформенные грабли',
            dateString: 'апрель 2016',
            tags: ['mobile', 'xamarin'],
            linkToVideo: 'https://www.youtube.com/watch?v=Ktc7ns2Z2Rw&index=6&list=PLRdS-n5seLRrSqdcVMqQge9YRcQztqgbO',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQcmRKOHVUU0E2Uzg',
        },
        {
            image: konovalovImage,
            speakerFullName: 'Никита Коновалов, Юлия Петрунина',
            eventName: 'DUMP',
            title: 'Тернистый путь принятия решений',
            dateString: 'март 2015',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=KB48F8s7jzY&index=3&list=PLRdS-n5seLRrEb91BeyQfcRJCOwb7issv',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2015-46259341',
        },
        {
            image: sobolevaImage,
            speakerFullName: 'Эльвира Соболева',
            eventName: 'DUMP',
            title: 'Тестировщик в роли менеджера итерации',
            dateString: 'март 2015',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=qyJ4Uf0FmGE&list=PLRdS-n5seLRp_rmnC69UpyhiPpo1tRYLv&index=3',
            linkToSlides: 'http://www.slideshare.net/it-people/ss-46260346',
        },
        {
            image: vdovichenkoImage,
            speakerFullName: 'Антон Вдовиченко',
            eventName: 'DUMP',
            title: 'Как тестировщик мануалы писал',
            dateString: 'март 2015',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=FtPX19c76l8&list=PLRdS-n5seLRp_rmnC69UpyhiPpo1tRYLv&index=2',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2015-46260163',
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: 'DUMP',
            title: 'Обучение разработчиков?!! Я думал они как-нибудь сами...',
            dateString: 'март 2015',
            tags: ['management', 'education'],
            linkToVideo: 'https://www.youtube.com/watch?v=80YK0oqJhC4&list=PLRdS-n5seLRrR2gBuM7Kt1yIizNGIrnM9&index=6',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2015-46489805',
        },
        {
            image: kirpichnikovImage,
            speakerFullName: 'Алексей Кирпичников',
            eventName: 'DUMP',
            title: 'Свежие новости из мира слабо полностью антисимметричных квазигрупп десятого порядка',
            dateString: 'март 2015',
            tags: ['science', 'math'],
            linkToVideo: 'https://www.youtube.com/watch?v=cwKnHHRutUs&index=6&list=PLRdS-n5seLRp6nwfAcqo7DTXta5GcclMq',
            linkToSlides: 'http://www.slideshare.net/it-people/ss-k',
        },
        {
            image: burmistrovImage,
            speakerFullName: 'Иван Бурмистров, Александр Казаков, Иван Дашкевич',
            eventName: 'DUMP',
            title: 'Микросервисная архитектура в теории и на практике',
            dateString: 'март 2015',
            tags: ['backend', 'architecture'],
            linkToVideo: 'https://www.youtube.com/watch?v=LDTa2Nx5qrw&list=PLRdS-n5seLRpIYtTllDAneJivR5Xea3nQ&index=6',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQam9KbUlrOFFzWTQ/view?usp=sharing',
        },
        {
            image: khruschevImage,
            speakerFullName: 'Михаил Хрущев',
            eventName: 'DUMP',
            title: 'Сайты в Фокусе',
            dateString: 'март 2015',
            tags: ['backend'],
            linkToVideo: 'https://www.youtube.com/watch?v=tZ7wYPXhQh8&list=PLRdS-n5seLRpIYtTllDAneJivR5Xea3nQ&index=2',
            linkToSlides: 'http://prezi.com/9ivkpl5qwtxx/',
        },
    ],
};
