import React from 'react';

import ahmetovImage from 'talks-image-responsive!./images/talks/ahmetov.jpg';
import baranovaImage from 'talks-image-responsive!./images/talks/baranova.jpg';
import bukharinomelkovImage from 'talks-image-responsive!./images/talks/bukharinomelkov.jpg';
import burmistrovImage from 'talks-image-responsive!./images/talks/burmistrov.jpg';
import chevdarImage from 'talks-image-responsive!./images/talks/chevdar.jpg';
import chicherskyImage from 'talks-image-responsive!./images/talks/chichersky.png';
import cherkasskiyImage from 'talks-image-responsive!./images/talks/cherkasskiy.png';
import chupriyanovImage from 'talks-image-responsive!./images/talks/chupriyanov.jpg';
import dashkevichImage from 'talks-image-responsive!./images/talks/dashkevich.jpg';
import dolganovImage from 'talks-image-responsive!./images/talks/dolganov.jpg';
import egorovImage from 'talks-image-responsive!./images/talks/egorov.jpg';
import geinImage from 'talks-image-responsive!./images/talks/gein.png';
import goldbergImage from 'talks-image-responsive!./images/talks/goldberg.jpg';
import golubevImage from 'talks-image-responsive!./images/talks/golubev.png';
import ivanovImage from 'talks-image-responsive!./images/talks/ivanov.png';
import kazakovImage from 'talks-image-responsive!./images/talks/kazakov.jpg';
import kharlovImage from 'talks-image-responsive!./images/talks/kharlov.png';
import khazamovImage from 'talks-image-responsive!./images/talks/khazamov.png';
import khruschevImage from 'talks-image-responsive!./images/talks/khruschev.jpg';
import kirpichnikovImage from 'talks-image-responsive!./images/talks/kirpichnikov.jpg';
import kokovinImage from 'talks-image-responsive!./images/talks/kokovin.jpg';
import konovalovImage from 'talks-image-responsive!./images/talks/konovalov.png';
import koshelevImage from 'talks-image-responsive!./images/talks/koshelev.png';
import koshelev2Image from 'talks-image-responsive!./images/talks/koshelev2.jpg';
import kurpilanskyImage from 'talks-image-responsive!./images/talks/kurpilansky.png';
import kutovoiImage from 'talks-image-responsive!./images/talks/kutovoi.png';
import kuzminImage from 'talks-image-responsive!./images/talks/kuzmin.png';
import larkovImage from 'talks-image-responsive!./images/talks/larkov.jpg';
import mahnoImage from 'talks-image-responsive!./images/talks/mahno.jpg';
import moiseevImage from 'talks-image-responsive!./images/talks/moiseev.png';
import mokhovaImage from 'talks-image-responsive!./images/talks/mokhova.jpg';
import musinaImage from 'talks-image-responsive!./images/talks/musina.png';
import plinerImage from 'talks-image-responsive!./images/talks/pliner.jpg';
import ratkinImage from 'talks-image-responsive!./images/talks/ratkin.png';
import ratnerImage from 'talks-image-responsive!./images/talks/ratner.jpg';
import romanovskyaImage from 'talks-image-responsive!./images/talks/romanovskya.png';
import romanovskyeImage from 'talks-image-responsive!./images/talks/romanovskye.jpg';
import ronzhinaImage from 'talks-image-responsive!./images/talks/ronzhina.png';
import roschupkinImage from 'talks-image-responsive!./images/talks/roschupkin.jpg';
import safarovImage from 'talks-image-responsive!./images/talks/safarov.png';
import shaihutdinovImage from 'talks-image-responsive!./images/talks/shaihutdinov.png';
import shishkinImage from 'talks-image-responsive!./images/talks/shishkin.jpg';
import sobolevaeImage from 'talks-image-responsive!./images/talks/sobolevae.jpg';
import sobolevaoImage from 'talks-image-responsive!./images/talks/sobolevao.png';
import solovievImage from 'talks-image-responsive!./images/talks/soloviev.jpg';
import sosninImage from 'talks-image-responsive!./images/talks/sosnin.jpg';
import suslovImage from 'talks-image-responsive!./images/talks/suslov.jpg';
import syrykhImage from 'talks-image-responsive!./images/talks/syrykh.jpg';
import tihonovImage from 'talks-image-responsive!./images/talks/tihonov.jpg';
import titarenkoImage from 'talks-image-responsive!./images/talks/titarenko.png';
import ustuzhaninImage from 'talks-image-responsive!./images/talks/ustuzhanin.png';
import vdovichenkoImage from 'talks-image-responsive!./images/talks/vdovichenko.png';
import volokitinImage from 'talks-image-responsive!./images/talks/volokitin.jpg';
import yuryevImage from 'talks-image-responsive!./images/talks/yuryev.png';
import zakharovImage from 'talks-image-responsive!./images/talks/zakharov.jpg';
import zhirovImage from 'talks-image-responsive!./images/talks/zhirov.png';
import tolstikovImage from 'talks-image-responsive!./images/talks/tolstikov.jpg';
import shatikhinImage from 'talks-image-responsive!./images/talks/shatikhin.jpg';
import bukharinImage from 'talks-image-responsive!./images/talks/bukharin.jpg';

// 2012 conference archives
const sqa2012Link = 'http://sqadays.com/ru/talks/7995';
const dump2012Link = 'http://dump-conf.ru/archive/2012/';

// 2013 conference archives
const dump2013Link = 'http://dump-it.ru/arhiv/itogi-dump-2013/';
const tadEkb2013Link = 'http://www.teamlead.ru/display/MAIN/TAD+4-2013+Ekaterinburg';
const profsouxMay2013Link = 'http://2013.profsoux.ru/';
const codefest2013Link = 'https://2013.codefest.ru/';

// 2014 conference archives
const dump2014Link = 'http://dump-conf.ru/archive/2014/';

// 2015 conference archives
const dump2015Link = 'http://dump-conf.ru/archive/2015/';
const secr2015Link = 'http://2015.secr.ru/';
const whaleRider2015Link = 'http://whalerider.ru/2015/';

// 2016 conference archives
const codefest2016Link = 'http://2016.codefest.ru/';
const dotnextPiter2016Link = 'http://2016.dotnext-piter.ru';
const dump2016Link = 'http://dump-conf.ru/archive/2016/';
const wsdEkb2016Link = 'https://wsd.events/2016/06/25/';

// 2017 conference archives
const dump2017Link = 'http://dump-conf.ru/archive/2017/';
const dotnext2017PiterLink = 'http://2017.dotnext-piter.ru';
const permTechTalksSep2017Link = 'https://vk.com/permtechtalks';
const izhTechTalksOct2017Link = 'https://vk.com/izhtechtalks';
const profsouxApr2017Link = 'http://2017.profsoux.ru/';
const cultDigital2017Link = 'http://cult.digital';

// 2018 conference archives

// conference and meetup archives without dates
const uralJSLink = 'https://vk.com/uraljs';
const dotnetEkbLink = 'https://vk.com/dotnetekb';
const UXSreda = 'https://www.facebook.com/UXSreda/';
const UXResearchMeetup = 'https://goo.gl/j4TP1v';

export default {
    additionalFooterText:
        <noindex>
            Фотографии докладчиков взяты из видео выступлений и фотоархивов соответствующих конференций. Рядом с каждым выступлением есть
            ссылка на сайт конференции, который является источником фотографии.
        </noindex>,
    title: 'Выступления и доклады сотрудников компании СКБ Контур',
    meta: {
        keywords: 'выступления, доклады, презентации, скб контур, скб-контур, контур, видео, презентации',
        description: 'Выступления и доклады сотрудников компании СКБ Контур на конференциях c видео и презентациями',
    },
    customMetaHeaders: [
        { ['http-equiv']: 'content-language', ['content']: 'ru-RU' },
    ],
    items: [
        {
            image: bukharinImage,
            speakerFullName: 'Вячеслав Бухарин',
            eventName: 'UralJS',
            title: 'Улучшение навигации в SPA',
            dateString: 'апрель 2018',
            tags: ['frontend'],
            linkToVideo: 'https://www.youtube.com/watch?v=Ip1C4rcfdi0',
            linkToSlides: 'https://slides.com/viacheslavbukharin/deck-2#/',
            linkToEvent: uralJSLink,
        },
        {
            image: tihonovImage,
            speakerFullName: 'Евгений Тихонов',
            eventName: 'UralJS',
            title: 'Давайте уже разберемся с DateTime',
            dateString: 'апрель 2018',
            tags: ['frontend'],
            linkToVideo: 'https://www.youtube.com/watch?v=Yc623xx6b3M&t=',
            linkToSlides: 'https://goo.gl/3qdeSp',
            linkToEvent: uralJSLink,
        },
        {
            image: shatikhinImage,
            speakerFullName: 'Михаил Шатихин',
            eventName: 'UralJS',
            title: 'Безжалостная типизация',
            dateString: 'февраль 2018',
            tags: ['frontend'],
            linkToVideo: 'https://www.youtube.com/watch?v=_00hPGacr18',
            linkToSlides: 'https://goo.gl/E4fmL1',
            linkToEvent: uralJSLink,
        },
        {
            image: khazamovImage,
            speakerFullName: 'Теймураз Хазамов',
            eventName: 'UralJS',
            title: 'React-DnD',
            dateString: 'ноябрь 2017',
            tags: ['frontend'],
            linkToVideo: 'https://www.youtube.com/watch?v=amhSyi_NQ4s&t=',
            linkToSlides: 'https://slides.com/t1mmaas/react-dnd/',
            linkToEvent: uralJSLink,
        },
        {
            image: tolstikovImage,
            speakerFullName: 'Владимир Толстиков',
            eventName: 'UralJS',
            title: 'CSS in JS',
            dateString: 'июль 2017',
            tags: ['frontend'],
            linkToVideo: 'https://www.youtube.com/watch?v=5HI7g3k0Ues&t=',
            linkToSlides: 'https://original001.github.io/reveal.js/',
            linkToEvent: uralJSLink,
        },
        {
            image: dolganovImage,
            speakerFullName: 'Лев Долганов',
            eventName: 'Cult.Digital',
            title: 'Опросы usability: методики и практики',
            dateString: 'ноябрь 2017',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=N61stg9SHFU',
            linkToSlides: 'https://drive.google.com/file/d/1kJnAvHnszQDOxh3h91llawoj3lCkh1v-/view?usp=sharing',
            linkToEvent: cultDigital2017Link,
        },
        {
            image: koshelev2Image,
            speakerFullName: 'Григорий Кошелев',
            eventName: 'DotNext',
            title: 'Интеграция виртуальных машин .NET и JAVA',
            dateString: 'май 2017',
            tags: ['backend', '.net', 'java'],
            linkToVideo: 'https://www.youtube.com/watch?v=E3SfXloQdfw',
            linkToSlides: 'http://assets.contentful.com/9n3x4rtjlya6/468yGoReI80u0CewaOqS4C/cbfc9aef7b8ded4cc472440ff4c9686b/Gregory_Koshelev_Integrating_.NET_and_Java_virtual_machines.pdf',
            linkToEvent: dotnext2017PiterLink,
        },
        {
            image: suslovImage,
            speakerFullName: 'Юрий Суслов',
            eventName: 'Izh Tech Talks',
            title: 'Мониторинг ошибок в боевом окружении',
            dateString: 'октябрь 2017',
            tags: ['operations', 'monitoring', 'alerting'],
            linkToVideo: 'https://www.youtube.com/watch?v=Cw2C9yG_nZE&list=PLc82OEDeni8Ts3ldKIKKFlNHTKT7a_1jp',
            linkToSlides: 'https://goo.gl/gYkeUh',
            linkToEvent: izhTechTalksOct2017Link,
        },
        {
            image: zhirovImage,
            speakerFullName: 'Евгений Жиров',
            eventName: 'Izh Tech Talks',
            title: 'HTTP/2 via C#',
            dateString: 'октябрь 2017',
            tags: ['.net', 'http'],
            linkToVideo: 'https://www.youtube.com/watch?v=WfiJ4os9ya8&list=PLc82OEDeni8Ts3ldKIKKFlNHTKT7a_1jp&index=2',
            linkToSlides: 'https://goo.gl/iwXuJv',
            linkToEvent: izhTechTalksOct2017Link,
        },
        {
            image: cherkasskiyImage,
            speakerFullName: 'Сергей Черкасский',
            eventName: 'Izh Tech Talks',
            title: 'Страх и ненависть в .NET',
            dateString: 'октябрь 2017',
            tags: ['backend', '.net', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=3QIwWkRP3Uo&index=3&list=PLc82OEDeni8Ts3ldKIKKFlNHTKT7a_1jp',
            linkToSlides: 'https://goo.gl/AH4dGt',
            linkToEvent: izhTechTalksOct2017Link,
        },
        {
            image: shishkinImage,
            speakerFullName: 'Евгений Шишкин',
            eventName: 'Izh Tech Talks',
            title: 'Как стать разработчиком-звездой',
            dateString: 'октябрь 2017',
            tags: ['management', 'hr'],
            linkToVideo: 'https://www.youtube.com/watch?v=BhJ4X1mZTYA&index=4&list=PLc82OEDeni8Ts3ldKIKKFlNHTKT7a_1jp',
            linkToSlides: 'https://goo.gl/RbwvVA',
            linkToEvent: izhTechTalksOct2017Link,
        },
        {
            image: cherkasskiyImage,
            speakerFullName: 'Сергей Черкасский',
            eventName: 'Perm Tech Talks',
            title: 'Страх и ненависть в .NET',
            dateString: 'сентябрь 2017',
            tags: ['backend', '.net', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=iVoBjO3ctqg&index=5&list=PLc82OEDeni8TyujauVY7DBM_dA1hZl2tK',
            linkToSlides: 'https://goo.gl/LEnB4N',
            linkToEvent: permTechTalksSep2017Link,
        },
        {
            image: roschupkinImage,
            speakerFullName: 'Виталий Рощупкин',
            eventName: 'Perm Tech Talks',
            title: 'Как помочь разработчику побороть legacy',
            dateString: 'сентябрь 2017',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=8qEgBdgFCtE&list=PLc82OEDeni8TyujauVY7DBM_dA1hZl2tK&index=4',
            linkToSlides: 'https://goo.gl/Dc3hgK',
            linkToEvent: permTechTalksSep2017Link,
        },
        {
            image: zhirovImage,
            speakerFullName: 'Евгений Жиров',
            eventName: 'Perm Tech Talks',
            title: 'Как обложить сервис метриками и не облажаться',
            dateString: 'сентябрь 2017',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=1WvnifkND2g&index=3&list=PLc82OEDeni8TyujauVY7DBM_dA1hZl2tK',
            linkToSlides: 'https://goo.gl/CqDjrN',
            linkToEvent: permTechTalksSep2017Link,
        },
        {
            image: kuzminImage,
            speakerFullName: 'Валерий Кузьмин',
            eventName: 'Perm Tech Talks',
            title: 'Как писать код, который пишет код на TypeScript',
            dateString: 'сентябрь 2017',
            tags: ['frontend'],
            linkToVideo: 'https://www.youtube.com/watch?v=Ra5bSK0M-Bo&index=2&list=PLc82OEDeni8TyujauVY7DBM_dA1hZl2tK',
            linkToSlides: 'https://goo.gl/APYbJW',
            linkToEvent: permTechTalksSep2017Link,
        },
        {
            image: yuryevImage,
            speakerFullName: 'Евгений Юрьев',
            eventName: 'Perm Tech Talks',
            title: 'Как писать код, который пишет код на MSIL',
            dateString: 'сентябрь 2017',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=U1v_ZQydnpU&index=1&list=PLc82OEDeni8TyujauVY7DBM_dA1hZl2tK',
            linkToSlides: 'https://goo.gl/f3U9Eb',
            linkToEvent: permTechTalksSep2017Link,
        },
        {
            image: dolganovImage,
            speakerFullName: 'Лев Долганов',
            eventName: 'ProfsoUX',
            title: 'Обратная связь в большом проекте и как извлечь из неё максимум пользы',
            dateString: 'апрель 2017',
            tags: ['design'],
            linkToVideo: 'https://vimeo.com/213398072',
            linkToSlides: 'https://goo.gl/4uKcfk',
            linkToEvent: profsouxApr2017Link,
        },
        {
            image: goldbergImage,
            speakerFullName: 'Игорь Гольдберг',
            eventName: 'DUMP',
            title: 'Не верь, не бойся, не проси!',
            dateString: 'апрель 2017',
            tags: ['management'],
            linkToVideo: 'https://www.youtube.com/watch?v=f_kW1m3Jr0g',
            linkToSlides: 'https://www.slideshare.net/it-people/ss-75274678',
            linkToEvent: dump2017Link,
        },
        {
            image: syrykhImage,
            speakerFullName: 'Максим Сырых',
            eventName: 'UralJS',
            title: 'Фантастический WebAudio и где его искать',
            dateString: 'апрель 2017',
            tags: ['frontend', 'js'],
            linkToVideo: 'https://www.youtube.com/watch?v=EXX5HmD_5lU&index=1&list=PLVxsRDo37_Zdda1PEmbGomFbisl9O3vU1',
            linkToSlides: 'https://slogger.github.io/webaudio-uraljs/',
            linkToEvent: uralJSLink,
        },
        {
            image: bukharinomelkovImage,
            speakerFullName: 'Вячеслав Бухарин, Денис Омельков',
            eventName: 'UralJS',
            title: 'Трудности перехода',
            dateString: 'апрель 2017',
            tags: ['frontend', 'js'],
            linkToVideo: 'https://www.youtube.com/watch?v=O-GBvIrKEA0&list=PLVxsRDo37_Zdda1PEmbGomFbisl9O3vU1&index=2',
            linkToSlides: 'http://slides.com/denisomelkov/deck#/',
            linkToEvent: uralJSLink,
        },
        {
            image: roschupkinImage,
            speakerFullName: 'Анна Бандура, Виталий Рощупкин, Антон Рычков, Дмитрий Якин',
            eventName: 'DUMP',
            title: 'Хотели как лучше, а не получилось',
            dateString: 'апрель 2017',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=HbQm006nKho',
            linkToEvent: dump2017Link,
        },
        {
            image: zakharovImage,
            speakerFullName: 'Максим Захаров, Лена Зырянова, Илария Тарасова',
            eventName: 'DUMP',
            title: 'Другое тестирование',
            dateString: 'апрель 2017',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=rWciwbsdZNw',
            linkToSlides: 'https://www.slideshare.net/it-people/ss-75225231',
            linkToEvent: dump2017Link,
        },
        {
            image: mokhovaImage,
            speakerFullName: 'Екатерина Мохова, Ксения Ильиных',
            eventName: 'DUMP',
            title: 'Авантюрное тестирование интерфейса',
            dateString: 'апрель 2017',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=t_zKEjuiins',
            linkToSlides: 'https://speakerdeck.com/kseniailinyh/avantiurnoie-tiestirovaniie-intierfieisa',
            linkToEvent: dump2017Link,
        },
        {
            image: ronzhinaImage,
            speakerFullName: 'Анастасия Ронжина',
            eventName: 'DUMP',
            title: 'UTC. Первые шаги',
            dateString: 'апрель 2017',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=guTLoaG3FVE',
            linkToSlides: 'https://www.slideshare.net/it-people/utc-75224418',
            linkToEvent: dump2017Link,
        },
        {
            image: kirpichnikovImage,
            speakerFullName: 'Алексей Кирпичников',
            eventName: 'DUMP',
            title: 'Не очень легко сгенерировать пять случайных чисел',
            dateString: 'апрель 2017',
            tags: ['science', 'math'],
            linkToVideo: 'https://www.youtube.com/watch?v=DyBzCcQWhCc',
            linkToSlides: 'https://www.slideshare.net/it-people/ss-75225566',
            linkToEvent: dump2017Link,
        },
        {
            image: ustuzhaninImage,
            speakerFullName: 'Игорь Устюжанин',
            eventName: 'Whale Rider',
            title: 'Комната с опускающимся потолком',
            dateString: 'май 2015',
            tags: ['management'],
            linkToVideo: 'https://youtu.be/O8JATNfHchk',
            linkToSlides: 'https://www.slideshare.net/profyclub_ru/ss-57647978',
            linkToEvent: whaleRider2015Link,
        },
        {
            image: romanovskyaImage,
            speakerFullName: 'Алексей Романовский',
            eventName: '.NET meetup Екб',
            title: 'Незнакомый знакомый Guid',
            dateString: 'апрель 2017',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=5wgmrgy-nfk',
            linkToSlides: 'https://vk.com/doc1499661_445544260?hash=cb82598b05e8923f74&dl=c556b4f844bc751492',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: romanovskyeImage,
            speakerFullName: 'Евгений Романовский',
            eventName: '.NET meetup Екб',
            title: 'Использование парсер-комбинаторов на Sprache для построения DSL',
            dateString: 'апрель 2017',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=MxQXsKXRCwI',
            linkToSlides: 'https://vk.com/doc1499661_445544533?hash=74bf943f41e26bf0f3&dl=e330f4869d6530ebce',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: sosninImage,
            speakerFullName: 'Иван Соснин',
            eventName: 'UralJS',
            title: 'Управление армией сайд-эффектов',
            dateString: 'февраль 2017',
            tags: ['frontend', 'js'],
            linkToVideo: 'https://youtu.be/UFr7eA7Hx0Y',
            linkToSlides: 'https://slides.com/vansosnin/saga',
            linkToEvent: uralJSLink,
        },
        {
            image: kuzminImage,
            speakerFullName: 'Валерий Кузьмин',
            eventName: 'UralJS',
            title: 'Обойдемся без бэкэнда',
            dateString: 'февраль 2017',
            tags: ['frontend', 'js'],
            linkToVideo: 'https://youtu.be/JrLv1UY2NLE',
            linkToSlides: 'https://slides.com/malcoriel/sls-at-uraljs',
            linkToEvent: uralJSLink,
        },
        {
            image: ivanovImage,
            speakerFullName: 'Кирилл Иванов',
            eventName: '.NET meetup Екб',
            title: 'F# + DDD',
            dateString: 'февраль 2017',
            tags: ['backend', '.net'],
            linkToVideo: 'https://youtu.be/bA4B5FskQDM',
            linkToSlides: 'http://slides.com/koteek/fsharpddd',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: koshelevImage,
            speakerFullName: 'Григорий Кошелев',
            eventName: '.NET meetup Екб',
            title: 'Интеграция виртуальных машин .NET и JAVA',
            dateString: 'февраль 2017',
            tags: ['backend', '.net', 'java'],
            linkToVideo: 'https://youtu.be/wyIlV4TU_Vk',
            linkToSlides: 'https://vk.com/doc1499661_443130256?hash=c79b834120f09169a3&dl=08bf31d5ab21f036fc',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: ratnerImage,
            speakerFullName: 'Светлана Ратнер, Аня Кукаркина',
            eventName: 'UX-Research Meetup',
            title: 'Работать в поле и не спалиться',
            dateString: 'январь 2017',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=GCCFe_zxG-U',
            linkToSlides: '',
            linkToEvent: UXResearchMeetup,
        },
        {
            image: tihonovImage,
            speakerFullName: 'Евгений Тихонов',
            eventName: 'UralJS',
            title: 'Тестирование реакт-компонент с enzyme',
            dateString: 'декабрь 2016',
            tags: ['frontend', 'js', 'react'],
            linkToVideo: 'https://www.youtube.com/watch?v=w1AGie9yHsg&list=PLVxsRDo37_Zc42OJkyeKzqxR6gda70B0C&index=3',
            linkToSlides: 'https://yadi.sk/d/NaFX7Fg8342VT9',
            linkToEvent: uralJSLink,
        },
        {
            image: khazamovImage,
            speakerFullName: 'Теймураз Хазамов',
            eventName: 'UralJS',
            title: 'Observable в JavaScript?',
            dateString: 'декабрь 2016',
            tags: ['frontend', 'js'],
            linkToVideo: 'https://www.youtube.com/watch?v=-Nx7EdE6qaI&list=PLVxsRDo37_Zc42OJkyeKzqxR6gda70B0C&index=2',
            linkToSlides: 'http://slides.com/t1mmaas/observable#/',
            linkToEvent: uralJSLink,
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: 'UralJS',
            title: 'Firebase. Back-end не нужен!',
            dateString: 'декабрь 2016',
            tags: ['frontend', 'js'],
            linkToVideo: 'https://www.youtube.com/watch?v=tVO_kdKMufo&list=PLVxsRDo37_Zc42OJkyeKzqxR6gda70B0C',
            linkToSlides: 'https://github.com/xoposhiy/firebase-course',
            linkToEvent: uralJSLink,
        },
        {
            image: kharlovImage,
            speakerFullName: 'Алексей Харлов',
            eventName: '.NET meetup Екб',
            title: 'Автоматизация процесса сборки с помощью CAKE',
            dateString: 'сентябрь 2016',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=mGwO1Oj3ccA',
            linkToSlides: 'https://vk.com/doc1499661_438004265?hash=ded8a17a73a2a1444e&dl=14ee383b4306be04c3',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: romanovskyaImage,
            speakerFullName: 'Алексей Романовский',
            eventName: '.NET meetup Екб',
            title: 'Метрики и Metrics.NET',
            dateString: 'август 2016',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=wG2RspZV3jM',
            linkToSlides: 'https://vk.com/doc1499661_437863799?hash=72f98033b2acba4709&dl=59acd61708d8a99b16',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: titarenkoImage,
            speakerFullName: 'Дмитрий Титаренко',
            eventName: '.NET meetup Екб',
            title: 'Злопастные строки',
            dateString: 'август 2016',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=GshXidWUtvE',
            linkToSlides: 'https://vk.com/doc1499661_437863797?hash=f7bfd6ac190614ff35&dl=ba1e5f95a626d69f95',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: '.NET meetup Екб',
            title: 'Моки зло и другие полезные вредняшки',
            dateString: 'август 2016',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=8j83zfDxJPU',
            linkToSlides: 'https://vk.com/doc1499661_437863796?hash=cafa06d70432b2a8d2&dl=0ec102b3daf2fd2ea0',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: romanovskyeImage,
            speakerFullName: 'Павел Егоров, Евгений Романовский',
            eventName: '.NET meetup Екб',
            title: 'SOLID. А можно ли лучше?',
            dateString: 'июнь 2016',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=xUtqV4RCn80',
            linkToSlides: 'https://vk.com/doc1499661_437572110?hash=a21968e95acbe31db2&dl=0cb72903588e061282',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: chicherskyImage,
            speakerFullName: 'Александр Чичерский',
            eventName: '.NET meetup Екб',
            title: 'Асинхронность в NET или Потока нет!',
            dateString: 'июнь 2016',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=XfU8h9CcZV8',
            linkToSlides: 'https://vk.com/doc1499661_437572111?hash=34eeb78055874fbe52&dl=edc0d29dddaae429eb',
            linkToEvent: dotnetEkbLink,
        },
        {
            image: volokitinImage,
            speakerFullName: 'Павел Волокитин',
            eventName: 'FrontendFellows',
            title: 'Relay или не Relay',
            dateString: 'январь 2016',
            tags: ['frontend', 'js', 'react'],
            linkToVideo: 'https://www.youtube.com/watch?v=v5Fi-djuwZk',
            linkToSlides: 'http://www.slideshare.net/PavelVolokitin/frontfellows-relay-66758880',
        },
        {
            image: ratnerImage,
            speakerFullName: 'Светлана Ратнер',
            eventName: 'UX-Research Meetup',
            title: 'Модерируемые удаленные тестирования',
            dateString: 'март 2016',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=FRXkLvbUbsI',
            linkToSlides: '',
            linkToEvent: UXResearchMeetup,
        },
        {
            image: kazakovImage,
            speakerFullName: 'Александр Казаков',
            eventName: 'Codefest',
            title: 'Нетривиальное о репликации: как добиться высокой доступности',
            dateString: 'март 2016',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=LFpJGGs-kuo',
            linkToSlides: 'http://www.slideshare.net/codefest/ss-60114851',
            linkToEvent: codefest2016Link,
        },
        {
            image: chevdarImage,
            speakerFullName: 'Игорь Чевдарь',
            eventName: 'DotNext',
            title: 'Кодогенерация для оптимизации',
            dateString: 'июнь 2016',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=X35JVTJV1CE&list=PLtWrKx3nUGBeYn-pSCjEgBPL90SvpylZL&index=7',
            linkToSlides: 'http://public.jugru.org/dotnext/2016/spb/day_1/track_2/chevdar.pdf',
            linkToEvent: dotnextPiter2016Link,
        },
        {
            image: volokitinImage,
            speakerFullName: 'Павел Волокитин',
            eventName: 'WebStandartsDays',
            title: 'Меняем JavaScript с помощью JavaScript',
            dateString: 'июнь 2016',
            tags: ['frontend', 'js'],
            linkToVideo: 'https://www.youtube.com/watch?v=zoq95j3V43g',
            linkToSlides: 'http://www.slideshare.net/PavelVolokitin/javascript-javascript-66759016',
            linkToEvent: wsdEkb2016Link,
        },
        {
            image: tihonovImage,
            speakerFullName: 'Евгений Тихонов',
            eventName: 'WebStandartsDays',
            title: 'Готовим бизнес-лапшу на React и Redux',
            dateString: 'июнь 2016',
            tags: ['frontend', 'js', 'react'],
            linkToVideo: 'https://www.youtube.com/watch?v=OXsxo4gkqtQ',
            linkToSlides: 'https://reelm.github.io/wsd-2016-slides/wsd-2016-slides.zip',
            linkToEvent: wsdEkb2016Link,
        },
        {
            image: burmistrovImage,
            speakerFullName: 'Иван Бурмистров',
            eventName: 'Cassandra Summit',
            title: 'Digging Cassandra cluster',
            dateString: 'сентябрь 2015',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=t6utdWssBOM',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQX1FvSlgtaUtscFE',
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: 'SECR',
            title: 'Почему вам стоит организовать свою ИТ-конференцию и как это сделать',
            dateString: 'октябрь 2015',
            tags: ['management', 'education'],
            linkToVideo: 'http://0x1.tv/20151022BG',
            linkToSlides: 'http://0x1.tv/20151022BG',
            linkToEvent: secr2015Link,
        },
        {
            image: kazakovImage,
            speakerFullName: 'Александр Казаков',
            eventName: 'DUMP',
            title: 'Профилирование распределенных систем',
            dateString: 'апрель 2016',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=EpDgUZWjGLc&index=6&list=PLRdS-n5seLRriePAvTXvkl8mE20gPeDIp',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQY1Bpdi1PTndhOXc',
            linkToEvent: dump2016Link,
        },
        {
            image: larkovImage,
            speakerFullName: 'Алексей Ларьков',
            eventName: 'DUMP',
            title: 'Moira: Realtime alerting',
            dateString: 'апрель 2016',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=_MJdtHbiXPE&index=5&list=PLRdS-n5seLRriePAvTXvkl8mE20gPeDIp',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQQVcwUEpybmpIZVE/view?usp=drivesdk',
            linkToEvent: dump2016Link,
        },
        {
            image: ronzhinaImage,
            speakerFullName: 'Анастасия Ронжина',
            eventName: 'DUMP',
            title: 'Cообщество тестировщиков Екатеринбурга',
            dateString: 'апрель 2016',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=-4zAc7kWAhc&index=5&list=PLRdS-n5seLRoMRdNO1k1FeFeBMgBRRX6j',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQRmF5dHVuWU8tYlU',
            linkToEvent: dump2016Link,
        },
        {
            image: ratkinImage,
            speakerFullName: 'Кирилл Раткин',
            eventName: 'DUMP',
            title: 'Планирование развития автотестов',
            dateString: 'апрель 2016',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=4yrWt_b835k&index=4&list=PLRdS-n5seLRoMRdNO1k1FeFeBMgBRRX6j',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQSHRBaGhKVjRhMkE',
            linkToEvent: dump2016Link,
        },
        {
            image: golubevImage,
            speakerFullName: 'Александр Голубев',
            eventName: 'DUMP',
            title: 'Адаптация команды после увольнения сотрудников',
            dateString: 'апрель 2016',
            tags: ['management', 'hr'],
            linkToVideo: 'https://www.youtube.com/watch?v=pL6AFI5GpqM&index=3&list=PLRdS-n5seLRrEr-0A2koGR1a2tM9dM0an',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQQkxlNXRPZTFjRTA',
            linkToEvent: dump2016Link,
        },
        {
            image: moiseevImage,
            speakerFullName: 'Дмитрий Моисеев',
            eventName: 'DUMP',
            title: 'Xamarin: кроссплатформенные грабли',
            dateString: 'апрель 2016',
            tags: ['mobile', 'xamarin'],
            linkToVideo: 'https://www.youtube.com/watch?v=Ktc7ns2Z2Rw&index=6&list=PLRdS-n5seLRrSqdcVMqQge9YRcQztqgbO',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQcmRKOHVUU0E2Uzg',
            linkToEvent: dump2016Link,
        },
        {
            image: konovalovImage,
            speakerFullName: 'Никита Коновалов, Юлия Петрунина',
            eventName: 'DUMP',
            title: 'Тернистый путь принятия решений',
            dateString: 'март 2015',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=KB48F8s7jzY&index=3&list=PLRdS-n5seLRrEb91BeyQfcRJCOwb7issv',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2015-46259341',
            linkToEvent: dump2015Link,
        },
        {
            image: sobolevaeImage,
            speakerFullName: 'Эльвира Соболева',
            eventName: 'DUMP',
            title: 'Тестировщик в роли менеджера итерации',
            dateString: 'март 2015',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=qyJ4Uf0FmGE&list=PLRdS-n5seLRp_rmnC69UpyhiPpo1tRYLv&index=3',
            linkToSlides: 'http://www.slideshare.net/it-people/ss-46260346',
            linkToEvent: dump2015Link,
        },
        {
            image: vdovichenkoImage,
            speakerFullName: 'Антон Вдовиченко',
            eventName: 'DUMP',
            title: 'Как тестировщик мануалы писал',
            dateString: 'март 2015',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=FtPX19c76l8&list=PLRdS-n5seLRp_rmnC69UpyhiPpo1tRYLv&index=2',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2015-46260163',
            linkToEvent: dump2015Link,
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: 'DUMP',
            title: 'Обучение разработчиков?!! Я думал они как-нибудь сами...',
            dateString: 'март 2015',
            tags: ['management', 'education'],
            linkToVideo: 'https://www.youtube.com/watch?v=80YK0oqJhC4&list=PLRdS-n5seLRrR2gBuM7Kt1yIizNGIrnM9&index=6',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2015-46489805',
            linkToEvent: dump2015Link,
        },
        {
            image: kirpichnikovImage,
            speakerFullName: 'Алексей Кирпичников',
            eventName: 'DUMP',
            title: 'Свежие новости из мира слабо полностью антисимметричных квазигрупп десятого порядка',
            dateString: 'март 2015',
            tags: ['science', 'math'],
            linkToVideo: 'https://www.youtube.com/watch?v=cwKnHHRutUs&index=6&list=PLRdS-n5seLRp6nwfAcqo7DTXta5GcclMq',
            linkToSlides: 'http://www.slideshare.net/it-people/ss-k',
            linkToEvent: dump2015Link,
        },
        {
            image: burmistrovImage,
            speakerFullName: 'Иван Бурмистров, Александр Казаков, Иван Дашкевич',
            eventName: 'DUMP',
            title: 'Микросервисная архитектура в теории и на практике',
            dateString: 'март 2015',
            tags: ['backend', 'architecture'],
            linkToVideo: 'https://www.youtube.com/watch?v=LDTa2Nx5qrw&list=PLRdS-n5seLRpIYtTllDAneJivR5Xea3nQ&index=6',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQam9KbUlrOFFzWTQ/view?usp=sharing',
            linkToEvent: dump2015Link,
        },
        {
            image: khruschevImage,
            speakerFullName: 'Михаил Хрущев',
            eventName: 'DUMP',
            title: 'Сайты в Фокусе',
            dateString: 'март 2015',
            tags: ['backend'],
            linkToVideo: 'https://www.youtube.com/watch?v=tZ7wYPXhQh8&list=PLRdS-n5seLRpIYtTllDAneJivR5Xea3nQ&index=2',
            linkToSlides: 'http://prezi.com/9ivkpl5qwtxx/',
            linkToEvent: dump2015Link,
        },
        {
            image: dashkevichImage,
            speakerFullName: 'Иван Дашкевич, Иван Бурмистров, Павел Егоров',
            eventName: 'DUMP',
            title: 'Почему из нас не получилось хороших тимлидов',
            dateString: 'март 2014',
            tags: ['management'],
            linkToVideo: 'https://www.youtube.com/watch?v=Fhd0L-cyp_s&list=PLRdS-n5seLRqJ-4fDXACGDMTz5JJH_gKy&index=4',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2014-34282193',
            linkToEvent: dump2014Link,
        },
        {
            image: shaihutdinovImage,
            speakerFullName: 'Рамиль Шайхутдинов',
            eventName: 'CodeFest',
            title: 'Шашечки или ехать?',
            dateString: 'март 2013',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=Svpn964JSyQ',
            linkToSlides: 'https://www.slideshare.net/UXkontur/ss-21111509',
            linkToEvent: codefest2013Link,
        },
        {
            image: mahnoImage,
            speakerFullName: 'Елена Махно',
            eventName: 'Profsoux',
            title: 'UX-исследования на всех этапах разработки продукта',
            dateString: 'май 2013',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=HoZJ9_PEzmw',
            linkToSlides: 'https://www.slideshare.net/ProfsoUX/ux-21491561',
            linkToEvent: profsouxMay2013Link,
        },
        {
            image: kazakovImage,
            speakerFullName: 'Александр Казаков',
            eventName: 'DUMP',
            title: 'О хранилище «Зебра»',
            dateString: 'май 2013',
            tags: ['backend', 'db', 'zebra'],
            linkToVideo: 'https://www.youtube.com/watch?v=8dvRoLPvCuo&list=PLRdS-n5seLRpVRDblg0KDFr5V4RlvaDiR&index=35',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2013-serverside',
            linkToEvent: dump2013Link,
        },
        {
            image: tihonovImage,
            speakerFullName: 'Евгений Тихонов',
            eventName: 'CassandraConf',
            title: 'Введение в Cassandra',
            dateString: 'декабрь 2013',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=ByoMdUB8iyI&list=PLEbtM8n7mz93h4VRGBc3SabsAHJCcjdzx&index=9',
            linkToSlides: 'https://yadi.sk/i/AIMcMN9XwgugQ',
        },
        {
            image: burmistrovImage,
            speakerFullName: 'Иван Бурмистров',
            eventName: 'CassandraConf',
            title: 'Строго ориентированная последовательность временных событий',
            dateString: 'декабрь 2013',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=M_rIdjpybH4&index=11&list=PLEbtM8n7mz93h4VRGBc3SabsAHJCcjdzx',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQU1J5bDhtaEpOV1E',
        },
        {
            image: chupriyanovImage,
            speakerFullName: 'Николай Чуприянов',
            eventName: 'DUMP',
            title: 'Каракули прокачивают извилины',
            dateString: 'март 2014',
            tags: ['design'],
            linkToVideo: 'https://vimeo.com/90720580',
            linkToSlides: 'https://www.slideshare.net/UXkontur/ss-32973619',
            linkToEvent: dump2014Link,
        },
        {
            image: geinImage,
            speakerFullName: 'Андрей Гейн',
            eventName: 'DUMP',
            title: 'Что мы делали с большими графами, чтобы на них было интересно смотреть',
            dateString: 'март 2014',
            tags: ['science', 'math'],
            linkToVideo: 'https://www.youtube.com/watch?v=DWm5pPSFA_Y&list=PLRdS-n5seLRoUXuEiUfbuvwDpvLtdsz_q&index=2',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2014-32925064',
            linkToEvent: dump2014Link,
        },
        {
            image: kutovoiImage,
            speakerFullName: 'Владимир Кутовой',
            eventName: 'DUMP',
            title: 'Keep Calm',
            dateString: 'март 2014',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=1mlHf0hNiUA&index=5&list=PLRdS-n5seLRq-L42Z42xb-uW2iGotkDWU',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQVXYzTUhnZjhCeFE/view?usp=drivesdk',
            linkToEvent: dump2014Link,
        },
        {
            image: plinerImage,
            speakerFullName: 'Лев Плинер',
            eventName: 'DUMP',
            title: '30 спартанцев: как совершить подвиг и не потерять команду',
            dateString: 'март 2014',
            tags: ['management', 'hr'],
            linkToVideo: 'https://www.youtube.com/watch?v=fFfTVAGoDTM&list=PLRdS-n5seLRqJ-4fDXACGDMTz5JJH_gKy&index=2',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQYTdBd290eVJRTFE/view?usp=sharing',
            linkToEvent: dump2014Link,
        },
        {
            image: kokovinImage,
            speakerFullName: 'Александр Коковин',
            eventName: 'DUMP',
            title: 'Распределенный консенсус',
            dateString: 'март 2014',
            tags: ['backend', 'algorithms'],
            linkToVideo: 'https://www.youtube.com/watch?v=uiEMqEl10Ps&list=PLRdS-n5seLRp0KOpGrpnBNFRmd8K-RPTC&index=6',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQM2NzWE5kWXI2SFk/view?usp=drivesdk',
            linkToEvent: dump2014Link,
        },
        {
            image: ahmetovImage,
            speakerFullName: 'Александр Ахметов',
            eventName: 'DUMP',
            title: 'Когда тесты пишут разработчики',
            dateString: 'март 2014',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=tnEyjppqufk&list=PLRdS-n5seLRoTw3SB8oPRBrbgDiRPWLdi',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2014-32925242',
            linkToEvent: dump2014Link,
        },
        {
            image: baranovaImage,
            speakerFullName: 'Анна Баранова',
            eventName: 'DUMP',
            title: 'Геймификация как метод управления',
            dateString: 'май 2013',
            tags: ['management'],
            linkToVideo: 'https://www.youtube.com/watch?v=eTybEGIE1QE&list=PLRdS-n5seLRpVRDblg0KDFr5V4RlvaDiR&index=14',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQZndQSTFDNjlVdm8/view?usp=drivesdk',
            linkToEvent: dump2013Link,
        },
        {
            image: solovievImage,
            speakerFullName: 'Сергей Соловьев, Николай Чуприянов',
            eventName: 'DUMP',
            title: '武士道: путь воина в проектировании интерфейсов',
            dateString: 'май 2013',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=87lDgRxqTjY&index=27&list=PLRdS-n5seLRpVRDblg0KDFr5V4RlvaDiR',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2013-22373283',
            linkToEvent: dump2013Link,
        },
        {
            image: shaihutdinovImage,
            speakerFullName: 'Рамиль Шайхутдинов',
            eventName: 'DUMP',
            title: '«Дом качества» как инструмент анализа пользовательского опыта',
            dateString: 'май 2013',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=Wmq7K1R-E8M&index=22&list=PLRdS-n5seLRpVRDblg0KDFr5V4RlvaDiR',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2013-22088665',
            linkToEvent: dump2013Link,
        },
        {
            image: romanovskyeImage,
            speakerFullName: 'Евгений Романовский',
            eventName: 'Семинар IT-people',
            title: 'Опыт работы с фреймворком ASP.NET MVC',
            dateString: 'июнь 2013',
            tags: ['backend', '.net', 'asp'],
            linkToVideo: 'https://www.youtube.com/watch?v=As4pSEyN_7A&index=2&list=PLRdS-n5seLRpbtx-l9gXedNN3QC2wnukE',
            linkToSlides: 'https://1drv.ms/p/s!AulBT7iBDr036wCPYI-H0Zp7vtPT',
        },
        {
            image: safarovImage,
            speakerFullName: 'Эльдар Сафаров',
            eventName: 'Teamlead Atlassian Day',
            title: 'От WackoWiki к Confluence',
            dateString: 'апрель 2013',
            tags: ['management'],
            linkToVideo: 'https://www.youtube.com/watch?v=c92vn7EN76k',
            linkToSlides: 'http://www.slideshare.net/teamlead/teamlead-atlassian-day-42013-wacko-wiki-mediawiki-confluence',
            linkToEvent: tadEkb2013Link,
        },
        {
            image: musinaImage,
            speakerFullName: 'Анастасия Мусина',
            eventName: 'ConfeT&QA',
            title: 'Не закручивайте гайки!',
            dateString: 'октябрь 2013',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=VCIqpKLhRlo',
        },
        {
            image: musinaImage,
            speakerFullName: 'Анастасия Мусина',
            eventName: 'SQA Days',
            title: 'Как заводить баги понятно всем',
            dateString: 'апрель 2012',
            tags: ['testing'],
            linkToVideo: 'https://vimeo.com/42271611',
            linkToSlides: 'http://www.slideshare.net/VLDCORP/ss-12686469',
            linkToEvent: sqa2012Link,
        },
        {
            image: kurpilanskyImage,
            speakerFullName: 'Евгений Курпилянский',
            eventName: 'CassandraConf',
            title: 'Индексирование поверх Cassandra',
            dateString: 'декабрь 2013',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=ljcZVZGnM2I&index=6&list=PLEbtM8n7mz93h4VRGBc3SabsAHJCcjdzx',
        },
        {
            image: kokovinImage,
            speakerFullName: 'Сычев Максим, Коковин Александр',
            eventName: 'CassandraConf',
            title: 'Как мы переезжали на Cassandra',
            dateString: 'декабрь 2013',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=9iOBQPDvIgY&list=PLEbtM8n7mz93h4VRGBc3SabsAHJCcjdzx&index=7',
            linkToSlides: 'http://www.slideshare.net/it-people/cassandraconf2',
        },
        {
            image: sobolevaoImage,
            speakerFullName: 'Соболева Ольга, Иванов Кирилл',
            eventName: 'CassandraConf',
            title: 'Обработка транзакций на примере телекоммуникационной компании',
            dateString: 'декабрь 2013',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=BacY43GELrM&index=12&list=PLEbtM8n7mz93h4VRGBc3SabsAHJCcjdzx',
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: 'Семинар IT-people',
            title: 'Введение в машинное обучение',
            dateString: 'декабрь 2012',
            tags: ['science', 'machine learning'],
            linkToVideo: 'https://www.youtube.com/watch?v=qzs0rJscOxg&index=2&list=PLRdS-n5seLRoCss8j5S-M50hH0HhoPiSo',
            linkToSlides: 'http://www.slideshare.net/xoposhiy/oseminar-2012',
        },
        {
            image: dashkevichImage,
            speakerFullName: 'Семён Молотков, Иван Дашкевич',
            eventName: 'DUMP',
            title: 'Канбан-победитель',
            dateString: 'март 2012',
            tags: ['management'],
            linkToVideo: 'https://www.youtube.com/watch?v=Pb5v__j91uY',
            linkToSlides: 'https://www.slideshare.net/UXkontur/ss-13193948',
            linkToEvent: dump2012Link,
        },
        {
            image: solovievImage,
            speakerFullName: 'Сергей Соловьёв, Семён Молотков',
            eventName: 'UX-Среда',
            title: 'Как не делать лишнего, или доклад без названия',
            dateString: 'март 2012',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=vEjo17JdYg4',
            linkToSlides: 'https://www.slideshare.net/UXkontur/ss-13265788',
            linkToEvent: UXSreda,
        },
    ],
};
