import volokitinImage from 'talks-image-responsive!./images/volokitin.jpg';
import kazakovImage from 'talks-image-responsive!./images/kazakov.jpg';
import chevdarImage from 'talks-image-responsive!./images/chevdar.jpg';
import tihonovImage from 'talks-image-responsive!./images/tihonov.jpg';
import burmistrovImage from 'talks-image-responsive!./images/burmistrov.jpg';
import egorovImage from 'talks-image-responsive!./images/egorov.jpg';
import larkovImage from 'talks-image-responsive!./images/larkov.jpg';
import ronzhinaImage from 'talks-image-responsive!./images/ronzhina.png';
import ratkinImage from 'talks-image-responsive!./images/ratkin.png';
import golubevImage from 'talks-image-responsive!./images/golubev.png';
import moiseevImage from 'talks-image-responsive!./images/moiseev.png';
import konovalovImage from 'talks-image-responsive!./images/konovalov.png';
import sobolevaImage from 'talks-image-responsive!./images/soboleva.jpg';
import vdovichenkoImage from 'talks-image-responsive!./images/vdovichenko.png';
import kirpichnikovImage from 'talks-image-responsive!./images/kirpichnikov.jpg';
import khruschevImage from 'talks-image-responsive!./images/khruschev.jpg';
import geinImage from 'talks-image-responsive!./images/gein.png';
import kutovoiImage from 'talks-image-responsive!./images/kutovoi.png';
import plinerImage from 'talks-image-responsive!./images/pliner.jpg';
import kokovinImage from 'talks-image-responsive!./images/kokovin.jpg';
import ahmetovImage from 'talks-image-responsive!./images/ahmetov.jpg';
import dashkevichImage from 'talks-image-responsive!./images/dashkevich.jpg';
import baranovaImage from 'talks-image-responsive!./images/baranova.jpg';
import solovievImage from 'talks-image-responsive!./images/soloviev.jpg';
import shaihutdinovImage from 'talks-image-responsive!./images/shaihutdinov.png';
import romanovskyImage from 'talks-image-responsive!./images/romanovsky.png';
import safarovImage from 'talks-image-responsive!./images/safarov.png';

export default {
    title: 'Выступления и доклады сотрудников компании СКБ Контур',
    meta: {
        keywords: 'выступления, доклады, презентации, скб контур, скб-контур, контур, видео, презентации',
        description: 'Выступления и доклады сотрудников компании СКБ Контур на конференциях c видео и презентациями',
    },
    customMetaHeaders: [
        { ['http-equiv']: 'content-language', ['content']: 'ru-RU' },
    ],
    items: [
        {
            image: volokitinImage,
            speakerFullName: 'Павел Волокитин',
            eventName: 'FrontendFellows',
            title: 'Relay или не Relay',
            dateString: 'январь 2016',
            tags: ['frontend', 'js', 'react'],
            linkToVideo: 'https://www.youtube.com/watch?v=v5Fi-djuwZk',
            linkToSlides: 'http://www.slideshare.net/PavelVolokitin/frontfellows-relay-66758880',
        },
        {
            image: kazakovImage,
            speakerFullName: 'Александр Казаков',
            eventName: 'Codefest',
            title: 'Нетривиальное о репликации: как добиться высокой доступности',
            dateString: 'март 2016',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=LFpJGGs-kuo',
            linkToSlides: 'http://www.slideshare.net/codefest/ss-60114851',
        },
        {
            image: chevdarImage,
            speakerFullName: 'Игорь Чевдарь',
            eventName: 'DotNext',
            title: 'Кодогенерация для оптимизации',
            dateString: 'июнь 2016',
            tags: ['backend', '.net'],
            linkToVideo: 'https://www.youtube.com/watch?v=X35JVTJV1CE&list=PLtWrKx3nUGBeYn-pSCjEgBPL90SvpylZL&index=7',
            linkToSlides: 'http://public.jugru.org/dotnext/2016/spb/day_1/track_2/chevdar.pdf',
        },
        {
            image: volokitinImage,
            speakerFullName: 'Павел Волокитин',
            eventName: 'WebStandartsDays',
            title: 'Меняем JavaScript с помощью JavaScript',
            dateString: 'июнь 2016',
            tags: ['frontend', 'js'],
            linkToVideo: 'https://www.youtube.com/watch?v=zoq95j3V43g',
            linkToSlides: 'http://www.slideshare.net/PavelVolokitin/javascript-javascript-66759016',
        },
        {
            image: tihonovImage,
            speakerFullName: 'Евгений Тихонов',
            eventName: 'WebStandartsDays',
            title: 'Готовим бизнес-лапшу на React и Redux',
            dateString: 'июнь 2016',
            tags: ['frontend', 'js', 'react'],
            linkToVideo: 'https://www.youtube.com/watch?v=OXsxo4gkqtQ',
            linkToSlides: 'https://reelm.github.io/wsd-2016-slides/wsd-2016-slides.zip',
        },
        {
            image: burmistrovImage,
            speakerFullName: 'Иван Бурмистров',
            eventName: 'Cassandra Summit',
            title: 'Digging Cassandra cluster',
            dateString: 'сентябрь 2015',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=t6utdWssBOM',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQX1FvSlgtaUtscFE',
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: 'SECR',
            title: 'Почему вам стоит организовать свою ИТ-конференцию и как это сделать',
            dateString: 'октябрь 2015',
            tags: ['management', 'education'],
            linkToVideo: 'http://0x1.tv/20151022BG',
            linkToSlides: 'http://0x1.tv/20151022BG',
        },
        {
            image: kazakovImage,
            speakerFullName: 'Александр Казаков',
            eventName: 'DUMP',
            title: 'Профилирование распределенных систем',
            dateString: 'апрель 2016',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=EpDgUZWjGLc&index=6&list=PLRdS-n5seLRriePAvTXvkl8mE20gPeDIp',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQY1Bpdi1PTndhOXc',
        },
        {
            image: larkovImage,
            speakerFullName: 'Алексей Ларьков',
            eventName: 'DUMP',
            title: 'Moira: Realtime alerting',
            dateString: 'апрель 2016',
            tags: ['backend', 'operations'],
            linkToVideo: 'https://www.youtube.com/watch?v=_MJdtHbiXPE&index=5&list=PLRdS-n5seLRriePAvTXvkl8mE20gPeDIp',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQQVcwUEpybmpIZVE/view?usp=drivesdk',
        },
        {
            image: ronzhinaImage,
            speakerFullName: 'Анастасия Ронжина',
            eventName: 'DUMP',
            title: 'Cообщество тестировщиков Екатеринбурга',
            dateString: 'апрель 2016',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=-4zAc7kWAhc&index=5&list=PLRdS-n5seLRoMRdNO1k1FeFeBMgBRRX6j',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQRmF5dHVuWU8tYlU',
        },
        {
            image: ratkinImage,
            speakerFullName: 'Кирилл Раткин',
            eventName: 'DUMP',
            title: 'Планирование развития автотестов',
            dateString: 'апрель 2016',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=4yrWt_b835k&index=4&list=PLRdS-n5seLRoMRdNO1k1FeFeBMgBRRX6j',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQSHRBaGhKVjRhMkE',
        },
        {
            image: golubevImage,
            speakerFullName: 'Александр Голубев',
            eventName: 'DUMP',
            title: 'Адаптация команды после увольнения сотрудников',
            dateString: 'апрель 2016',
            tags: ['management', 'hr'],
            linkToVideo: 'https://www.youtube.com/watch?v=pL6AFI5GpqM&index=3&list=PLRdS-n5seLRrEr-0A2koGR1a2tM9dM0an',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQQkxlNXRPZTFjRTA',
        },
        {
            image: moiseevImage,
            speakerFullName: 'Дмитрий Моисеев',
            eventName: 'DUMP',
            title: 'Xamarin: кроссплатформенные грабли',
            dateString: 'апрель 2016',
            tags: ['mobile', 'xamarin'],
            linkToVideo: 'https://www.youtube.com/watch?v=Ktc7ns2Z2Rw&index=6&list=PLRdS-n5seLRrSqdcVMqQge9YRcQztqgbO',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQcmRKOHVUU0E2Uzg',
        },
        {
            image: konovalovImage,
            speakerFullName: 'Никита Коновалов, Юлия Петрунина',
            eventName: 'DUMP',
            title: 'Тернистый путь принятия решений',
            dateString: 'март 2015',
            tags: ['design'],
            linkToVideo: 'https://www.youtube.com/watch?v=KB48F8s7jzY&index=3&list=PLRdS-n5seLRrEb91BeyQfcRJCOwb7issv',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2015-46259341',
        },
        {
            image: sobolevaImage,
            speakerFullName: 'Эльвира Соболева',
            eventName: 'DUMP',
            title: 'Тестировщик в роли менеджера итерации',
            dateString: 'март 2015',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=qyJ4Uf0FmGE&list=PLRdS-n5seLRp_rmnC69UpyhiPpo1tRYLv&index=3',
            linkToSlides: 'http://www.slideshare.net/it-people/ss-46260346',
        },
        {
            image: vdovichenkoImage,
            speakerFullName: 'Антон Вдовиченко',
            eventName: 'DUMP',
            title: 'Как тестировщик мануалы писал',
            dateString: 'март 2015',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=FtPX19c76l8&list=PLRdS-n5seLRp_rmnC69UpyhiPpo1tRYLv&index=2',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2015-46260163',
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: 'DUMP',
            title: 'Обучение разработчиков?!! Я думал они как-нибудь сами...',
            dateString: 'март 2015',
            tags: ['management', 'education'],
            linkToVideo: 'https://www.youtube.com/watch?v=80YK0oqJhC4&list=PLRdS-n5seLRrR2gBuM7Kt1yIizNGIrnM9&index=6',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2015-46489805',
        },
        {
            image: kirpichnikovImage,
            speakerFullName: 'Алексей Кирпичников',
            eventName: 'DUMP',
            title: 'Свежие новости из мира слабо полностью антисимметричных квазигрупп десятого порядка',
            dateString: 'март 2015',
            tags: ['science', 'math'],
            linkToVideo: 'https://www.youtube.com/watch?v=cwKnHHRutUs&index=6&list=PLRdS-n5seLRp6nwfAcqo7DTXta5GcclMq',
            linkToSlides: 'http://www.slideshare.net/it-people/ss-k',
        },
        {
            image: burmistrovImage,
            speakerFullName: 'Иван Бурмистров, Александр Казаков, Иван Дашкевич',
            eventName: 'DUMP',
            title: 'Микросервисная архитектура в теории и на практике',
            dateString: 'март 2015',
            tags: ['backend', 'architecture'],
            linkToVideo: 'https://www.youtube.com/watch?v=LDTa2Nx5qrw&list=PLRdS-n5seLRpIYtTllDAneJivR5Xea3nQ&index=6',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQam9KbUlrOFFzWTQ/view?usp=sharing',
        },
        {
            image: khruschevImage,
            speakerFullName: 'Михаил Хрущев',
            eventName: 'DUMP',
            title: 'Сайты в Фокусе',
            dateString: 'март 2015',
            tags: ['backend'],
            linkToVideo: 'https://www.youtube.com/watch?v=tZ7wYPXhQh8&list=PLRdS-n5seLRpIYtTllDAneJivR5Xea3nQ&index=2',
            linkToSlides: 'http://prezi.com/9ivkpl5qwtxx/',
        },
        {
            image: dashkevichImage,
            speakerFullName: 'Иван Дашкевич, Иван Бурмистров, Павел Егоров',
            eventName: 'DUMP',
            title: 'Почему из нас не получилось хороших тимлидов',
            dateString: 'март 2014',
            tags: ['management'],
            linkToVideo: 'https://www.youtube.com/watch?v=Fhd0L-cyp_s&list=PLRdS-n5seLRqJ-4fDXACGDMTz5JJH_gKy&index=4',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2014-34282193',
        },
        {
            image: kazakovImage,
            speakerFullName: 'Александр Казаков',
            eventName: 'DUMP',
            title: 'О хранилище «Зебра»',
            dateString: 'май 2013',
            tags: ['backend', 'db', 'zebra'],
            linkToVideo: 'https://www.youtube.com/watch?v=8dvRoLPvCuo&list=PLRdS-n5seLRpVRDblg0KDFr5V4RlvaDiR&index=35',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2013-serverside',
        },
        {
            image: egorovImage,
            speakerFullName: 'Павел Егоров',
            eventName: 'Семинар IT-people',
            title: 'Введение в машинное обучение',
            dateString: 'декабрь 2012',
            tags: ['science', 'machine learning'],
            linkToVideo: 'https://www.youtube.com/watch?v=qzs0rJscOxg&index=2&list=PLRdS-n5seLRoCss8j5S-M50hH0HhoPiSo',
            linkToSlides: 'http://www.slideshare.net/xoposhiy/oseminar-2012',
        },
        {
            image: tihonovImage,
            speakerFullName: 'Евгений Тихонов',
            eventName: 'CassandraConf',
            title: 'Введение в Cassandra',
            dateString: 'декабрь 2013',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=ByoMdUB8iyI&list=PLEbtM8n7mz93h4VRGBc3SabsAHJCcjdzx&index=9',
            linkToSlides: 'https://yadi.sk/i/AIMcMN9XwgugQ',
        },
        {
            image: burmistrovImage,
            speakerFullName: 'Иван Бурмистров',
            eventName: 'CassandraConf',
            title: 'Строго ориентированная последовательность временных событий',
            dateString: 'декабрь 2013',
            tags: ['backend', 'db', 'cassandra'],
            linkToVideo: 'https://www.youtube.com/watch?v=M_rIdjpybH4&index=11&list=PLEbtM8n7mz93h4VRGBc3SabsAHJCcjdzx',
            linkToSlides: 'https://drive.google.com/open?id=0B-qtqQ5D71UQU1J5bDhtaEpOV1E',
        },
        {
            image: geinImage,
            speakerFullName: 'Андрей Гейн',
            eventName: 'DUMP',
            title: 'Что мы делали с большими графами, чтобы на них было интересно смотреть',
            dateString: 'март 2014',
            tags: ['science', 'math'],
            linkToVideo: 'https://www.youtube.com/watch?v=DWm5pPSFA_Y&list=PLRdS-n5seLRoUXuEiUfbuvwDpvLtdsz_q&index=2',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2014-32925064',
        },
        {
            image: kutovoiImage,
            speakerFullName: 'Владимир Кутовой',
            eventName: 'DUMP',
            title: 'Keep Calm',
            dateString: 'март 2014',
            tags: ['design', 'ui'],
            linkToVideo: 'https://www.youtube.com/watch?v=1mlHf0hNiUA&index=5&list=PLRdS-n5seLRq-L42Z42xb-uW2iGotkDWU',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQVXYzTUhnZjhCeFE/view?usp=drivesdk',
        },
        {
            image: plinerImage,
            speakerFullName: 'Лев Плинер',
            eventName: 'DUMP',
            title: '30 спартанцев: как совершить подвиг и не потерять команду',
            dateString: 'март 2014',
            tags: ['management', 'hr'],
            linkToVideo: 'https://www.youtube.com/watch?v=fFfTVAGoDTM&list=PLRdS-n5seLRqJ-4fDXACGDMTz5JJH_gKy&index=2',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQYTdBd290eVJRTFE/view?usp=sharing',
        },
        {
            image: kokovinImage,
            speakerFullName: 'Александр Коковин',
            eventName: 'DUMP',
            title: 'Распределенный консенсус',
            dateString: 'март 2014',
            tags: ['backend', 'algorithms'],
            linkToVideo: 'https://www.youtube.com/watch?v=uiEMqEl10Ps&list=PLRdS-n5seLRp0KOpGrpnBNFRmd8K-RPTC&index=6',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQM2NzWE5kWXI2SFk/view?usp=drivesdk',
        },
        {
            image: ahmetovImage,
            speakerFullName: 'Александр Ахметов',
            eventName: 'DUMP',
            title: 'Когда тесты пишут разработчики',
            dateString: 'март 2014',
            tags: ['testing'],
            linkToVideo: 'https://www.youtube.com/watch?v=tnEyjppqufk&list=PLRdS-n5seLRoTw3SB8oPRBrbgDiRPWLdi',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2014-32925242',
        },
        {
            image: baranovaImage,
            speakerFullName: 'Анна Баранова',
            eventName: 'DUMP',
            title: 'Геймификация как метод управления',
            dateString: 'май 2013',
            tags: ['management'],
            linkToVideo: 'https://www.youtube.com/watch?v=eTybEGIE1QE&list=PLRdS-n5seLRpVRDblg0KDFr5V4RlvaDiR&index=14',
            linkToSlides: 'https://drive.google.com/file/d/0B-qtqQ5D71UQZndQSTFDNjlVdm8/view?usp=drivesdk',
        },
        {
            image: solovievImage,
            speakerFullName: 'Сергей Соловьев, Николай Чуприянов',
            eventName: 'DUMP',
            title: '武士道: путь воина в проектировании интерфейсов',
            dateString: 'май 2013',
            tags: ['design', 'ui'],
            linkToVideo: 'https://www.youtube.com/watch?v=87lDgRxqTjY&index=27&list=PLRdS-n5seLRpVRDblg0KDFr5V4RlvaDiR',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2013-22373283',
        },
        {
            image: shaihutdinovImage,
            speakerFullName: 'Рамиль Шайхутдинов',
            eventName: 'DUMP',
            title: '«Дом качества» как инструмент анализа пользовательского опыта',
            dateString: 'май 2013',
            tags: ['design', 'ui'],
            linkToVideo: 'https://www.youtube.com/watch?v=Wmq7K1R-E8M&index=22&list=PLRdS-n5seLRpVRDblg0KDFr5V4RlvaDiR',
            linkToSlides: 'http://www.slideshare.net/it-people/dump2013-22088665',
        },
        {
            image: romanovskyImage,
            speakerFullName: 'Евгений Романовский',
            eventName: 'Семинар IT-people',
            title: 'Опыт работы с фреймворком ASP.NET MVC',
            dateString: 'июнь 2013',
            tags: ['backend', '.net', 'asp'],
            linkToVideo: 'https://www.youtube.com/watch?v=As4pSEyN_7A&index=2&list=PLRdS-n5seLRpbtx-l9gXedNN3QC2wnukE',
            linkToSlides: 'https://1drv.ms/p/s!AulBT7iBDr036wCPYI-H0Zp7vtPT',
        },
        {
            image: safarovImage,
            speakerFullName: 'Эльдар Сафаров',
            eventName: 'Teamlead Atlassian Day',
            title: 'От WackoWiki к Confluence',
            dateString: 'апрель 2014',
            tags: ['management'],
            linkToVideo: 'https://www.youtube.com/watch?v=c92vn7EN76k',
            linkToSlides: 'http://www.slideshare.net/teamlead/teamlead-atlassian-day-42013-wacko-wiki-mediawiki-confluence',
        },
    ],
};
